@startuml
Object User
Object Order
Object OrderDetails
Object Basket
Object Admin
Object CupcakeBottom
Object CupcakeTop

User *-- Order
Order *-- OrderDetails
OrderDetails *-- CupcakeBottom
OrderDetails *-- CupcakeTop

@enduml