@startuml
start
:Home page;
if (Bestil her) then (Logged in)
  :Order page;
else (Not Logged in)
  :Login page;
  if (Login) then (has user)
    :Home page;
  else (No user)
    :Create user page;
    note right
    Opretter en bruger i vores database
    end note
    :Login page;
    :Home page;
  endif
  : Order page;
endif
: Basket page;
: Order is successful;
note right
Tjekker om kunden har nok penge på sin konto og hvis han/hun har, bliver de trukket og ordren går igennem.
Alt info bliver gemt i databasen.
end note

stop
@enduml
